### ISSUE TITLE
F1_go refreshing page

### ISSUE THREAD

**Issue by knilssen** [crocotelementry/F1_2018_UDP#3]
When refreshing a page multiple times back to back this problem occurs. This problem does not happen when switching between pages, only when refreshing the same page multiple times back to back.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1153f46]

goroutine 26 [running]:
net.(*UDPConn).ReadFromUDP(0x0, 0xc00015c580, 0x53d, 0x53d, 0x53d, 0x53d, 0x0, 0x50)
	/usr/local/go/src/net/udpsock.go:106 +0x26
main.time_udp_client(0xc000078b00)
	/Users/kristiannilssen/Documents/GitHub/Go/src/github.com/knilssen/f1_go/go_websocket_server.go:289 +0xf3
created by main.time_wsHandler
	/Users/kristiannilssen/Documents/GitHub/Go/src/github.com/knilssen/f1_go/go_websocket_server.go:125 +0xf0
exit status 2
```

**Comment by knilssen** [comment]
Issue fixed with most recent commit to go_websocket_server.go

Issue was due to not closing the websocket connection to the browser window correctly and dealing with the close on our listning for udp packets. 

Fix was to bring our code that created our udp listener and socket as a global variable and then use that socket for our websocket handlers. Since we are looking for broadcasted packets on a port not just a specific IP and port, when we close our socket we cannon reconect again. This fix overcomes that by keeping our socket open for the duration of the program.

```
// Create a socket listing for udp packets on port 5003
// Since this is not on any specific ip address, if closed we can reopen on the same port again.
// To get over this hurdle, we brought the socket out to only declare once, and can be called by
// each of our websocket handlers to grab packets from the game
var addrs, _ = net.ResolveUDPAddr("udp", ":5003")
var sock, err = net.ListenUDP("udp", addrs)
```


We also added a defer statement to close the connection to the websocket as well at the beginning of our gorutine that is called within our websocket handlers. This closes the connection to the websocket when our writeJSON fails due to a disconnected websocket connection on the clients side. When this fails we return which in turn calls our defer statement to be called. 


With this fix we can now refresh pages while still keeping the server alive and keep on receiving live UDP packets from F1 2018.

We can also use our page navigation to navigate between Live and Time pages while this would also work with history but that page is yet to be created yet. 

Woohoo!

**Comment by knilssen** [comment]
Where we pass sock in our websocket handler for live in this example to our gorutine 

```
// Live data Websocket handler, when our javascriot file, which is served along with our html file from our
// root handler, runs it makes a websocket connection to ws://localhost:8080/ws which triggers our hsHandler with the trailing /ws.
// We then start our live_data_udp_client that listens for and formats the incoming UDP data from F1 2018 then writes the packets to our websocket
func live_wsHandler(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Print("upgrade:", err)
		return
	}
	go live_data_udp_client(conn, sock)
}
```

**Comment by knilssen** [comment]
Where we accept sock as one of our parameters and use our defer statement for the websocket connection. Notice at the end of each case statement we return. This small addition will call our defer statement made at the beginning of this gorutine.

```
func live_data_udp_client(conn *websocket.Conn, sock *net.UDPConn) {
  defer conn.Close()

  for {
    // Create a buffer to read the incoming udp packets
    // Read the udp packets and if we get an error while reading, print out the error
    buf := make([]byte, 1341)
    _, _, err := sock.ReadFromUDP(buf)
    if err != nil {
      fmt.Println("readfromudp error::: ",err)
    }

		// fmt.Println("buff", buf)

    // Set two new readers in which to cast into our structs.
    // One is for the header, which we determine what packet we have and then use the other
    // for the whole packet.
    header_bytes_reader := bytes.NewReader(buf[0:21])
    packet_bytes_reader := bytes.NewReader(buf)

    // Read the binary of the udp packet header into our struct
    if err := binary.Read(header_bytes_reader, binary.LittleEndian, &header); err != nil {
		    fmt.Println("binary.Read header failed:", err)
  	}

    // Depending on which packet we have, which we find by looking at header.M_packetId
    // We use a switch statement to then read the whole binary udp packet into its associated struct
    switch header.M_packetId {
    case 0:
        // If the packet we received is a motion_packet, read its binary into our motion_packet struct
        if err := binary.Read(packet_bytes_reader, binary.LittleEndian, &motion_packet); err != nil {
    		    fmt.Println("binary.Read motion_packet failed:", err)
      	}
				// Convert out struct into JSON format
        json_motion_packet, err := json.Marshal(motion_packet)
        if err != nil {
          fmt.Println(err)
        }
				// Write our JSON formatted F1 UDP packet struct to our websocket
        if err := conn.WriteMessage(websocket.TextMessage, json_motion_packet); err != nil {
    			log.Printf("Websocket error writing motion_packet: %s", err)
					return
    		}
				break
    case 1:
        // If the packet we received is the session_packet, read its binary into our session_packet struct
        if err := binary.Read(packet_bytes_reader, binary.LittleEndian, &session_packet); err != nil {
    		    fmt.Println("binary.Read session_packet failed:", err)
      	}
				// Convert out struct into JSON format
        json_session_packet, err := json.Marshal(session_packet)
        if err != nil {
          fmt.Println(err)
        }
				// Write our JSON formatted F1 UDP packet struct to our websocket
        if err := conn.WriteMessage(websocket.TextMessage, json_session_packet); err != nil {
    			log.Printf("Websocket error writing session_packet: %s", err)
					return
    		}
				break
    case 2:
        // If the packet we received is the lap_packet, read its binary into our lap_packet struct
        if err := binary.Read(packet_bytes_reader, binary.LittleEndian, &lap_packet); err != nil {
    		    fmt.Println("binary.Read lap_packet failed:", err)
      	}
				// Convert out struct into JSON format
        json_lap_packet, err := json.Marshal(lap_packet)
        if err != nil {
          fmt.Println(err)
        }
				// Write our JSON formatted F1 UDP packet struct to our websocket
        if err := conn.WriteMessage(websocket.TextMessage, json_lap_packet); err != nil {
    			log.Printf("Websocket error writing lap_packet: %s", err)
					return
    		}
				break
    case 3:
        // If the packet we received is the event_packet, read its binary into our event_packet struct
        if err := binary.Read(packet_bytes_reader, binary.LittleEndian, &event_packet); err != nil {
    		    fmt.Println("binary.Read event_packet failed:", err)
      	}
				// Convert out struct into JSON format
        json_event_packet, err := json.Marshal(event_packet)
        if err != nil {
          fmt.Println(err)
        }
				// Write our JSON formatted F1 UDP packet struct to our websocket
        if err := conn.WriteMessage(websocket.TextMessage, json_event_packet); err != nil {
    			log.Printf("Websocket error writing event_packet: %s", err)
					return
    		}
				break
    case 4:
        // If the packet we received is the participant_packet, read its binary into our participant_packet struct
        if err := binary.Read(packet_bytes_reader, binary.LittleEndian, &participant_packet); err != nil {
    		    fmt.Println("binary.Read participant_packet failed:", err)
      	}
				// Convert out struct into JSON format
        json_participant_packet, err := json.Marshal(participant_packet)
        if err != nil {
          fmt.Println(err)
        }
				// Write our JSON formatted F1 UDP packet struct to our websocket
        if err = conn.WriteMessage(websocket.TextMessage, json_participant_packet); err != nil {
    			log.Printf("Websocket error writing participant_packet: %s", err)
					return
    		}
				break
    case 5:
        // If the packet we received is the car_setup_packet, read its binary into our car_setup_packet struct
        if err := binary.Read(packet_bytes_reader, binary.LittleEndian, &car_setup_packet); err != nil {
    		    fmt.Println("binary.Read car_setup_packet failed:", err)
      	}
				// Convert out struct into JSON format
        json_car_setup_packet, err := json.Marshal(car_setup_packet)
        if err != nil {
          fmt.Println(err)
        }
				// Write our JSON formatted F1 UDP packet struct to our websocket
        if err := conn.WriteMessage(websocket.TextMessage, json_car_setup_packet); err != nil {
    			log.Printf("Websocket error writing car_setup_packet: %s", err)
					return
    		}
				break
    case 6:
        // If the packet we received is the telemetry_packet, read its binary into our telemetry_packet struct
        if err := binary.Read(packet_bytes_reader, binary.LittleEndian, &telemetry_packet); err != nil {
    		    fmt.Println("binary.Read telemetry_packet failed:", err)
      	}
        json_telemetry_packet, err := json.Marshal(telemetry_packet)
        if err != nil {
          fmt.Println(err)
        }
				// Write our JSON formatted F1 UDP packet struct to our websocket
        if err := conn.WriteMessage(websocket.TextMessage, json_telemetry_packet); err != nil {
    			log.Printf("Websocket error writing telemetry_packet: %s", err)
					return
    		}
				break
    case 7:
        // If the packet we received is the car_status_packet, read its binary into our car_status_packet struct
        if err := binary.Read(packet_bytes_reader, binary.LittleEndian, &car_status_packet); err != nil {
    		    fmt.Println("binary.Read car_status_packet failed:", err)
      	}
				// Convert out struct into JSON format
        json_car_status_packet, err := json.Marshal(car_status_packet)
        if err != nil {
          fmt.Println(err)
        }
				// Write our JSON formatted F1 UDP packet struct to our websocket
        if err := conn.WriteMessage(websocket.TextMessage, json_car_status_packet); err != nil {
    			log.Printf("Websocket error writing car_status_packet: %s", err)
					return
    		}
				break
    }

  }
}
```
